### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by LTizzle1212**
I tried updating the unit test but receiving the error "{'error': {'status': 400, 'message': 'No search query'}}". I tried troubleshooting it but had no luck. 

Has anyone seen that error before?

### CODE REVIEW

**Comment by rwalk651** [comment]
looks like you're declaring `artist_name_or_query` but not referencing it.

**Comment by LTizzle1212** [comment]
@rwalk651 - I was able to update the unit tests. Can you please review them at your earliest convenience?

**Comment by rwalk651** [comment]
@LTizzle1212 Did the tests work for you?

**Comment by LTizzle1212** [comment]
@rwalk651 - I was able to run successful tests on my end! I had to make some adjustments but got them to work

**Review by rwalk651 — APPROVED** [review]
Good start!

**Comment by LTizzle1212** [comment]
Confirmed merged unit test

**Pull request merged**
