### PR TITLE
added try and except

### PR DESCRIPTION
**Pull request by LTizzle1212**
Added try and except

### CODE REVIEW

**Comment by rwalk651** [comment]
@LTizzle1212 If I search anything I keep getting this error:
```
TypeError: The view function did not return a valid response tuple. The tuple must have the form (body, status, headers), (body, status), or (body, headers).
```
Can you confirm it works on your machine before I start digging through the code.

**Comment by LTizzle1212** [comment]
I'm still having issues on my end for this unfortunately! I may be doing something wrong on my end.

**Comment by rwalk651** [comment]
@LTizzle1212 No worries, if I have time tonight I can recreate app.py and test it on my end.

**Comment by HyungnaLim** [comment]
I implemented try-except block in app.py on spotify_error branch!
You can review the code on PR #19

**Comment by rwalk651** [comment]
Closing, implemented in PR #24

**Pull request closed without merging**
