### PR TITLE
error handling added on spotify module

### PR DESCRIPTION
**Pull request by HyungnaLim**
I created a class SpotifyError to return it whenever error occur from API calls.
Now app.py will render error.html page when there is SpotifyError returned.
I also added home link to error.html page for better UX.

### CODE REVIEW

**Comment by rwalk651** [comment]
@HyungnaLim Looks good, not sure how to invoke the various error codes. Do you have some screenshots of the error page being displayed with a couple error codes?

**Comment by HyungnaLim** [comment]
This is the search result when you search "=]" (which doesn't have matching artist data on spotify API)
Everything returns None, except the artist_name will be shown as the search string that user entered
image

**Comment by HyungnaLim** [comment]
after the latest commit, search result is showing as below.
image

**Comment by HyungnaLim** [comment]
Now when there's no matching artist, it will render error.html page with error message.
image

**Comment by rwalk651** [comment]
Because PR #24 takes care of error handling in `app.py`, modifying `app.py` in this PR is out of scope.

**Comment by HyungnaLim** [comment]
just checked the PR. I will update according to that by this weekend. thanks for the note!

**Pull request closed without merging**
