### PR TITLE
Added more spotify error handling

### PR DESCRIPTION
**Pull request by HyungnaLim**
Added if-else statements on search_result.html to handle errors from reading track information when there's no or less than 3 top tracks. Also, artist image will not appear if there's no artist image url found from api. When there's no genre, a message will be displayed instead of leaving the section empty. All data will be returned as None if they are not found from api.

Example search result of no artist image, no genre, only one track:
image

### CODE REVIEW

**Comment by HyungnaLim** [comment]
Note: This is a sub branch from db_data_handling!

**Comment by HyungnaLim** [comment]
I won't make more change for this branch from now! So, it's ready for final review

**Review by rwalk651 — APPROVED** [review]
looks good, will update db to handle Null entries.

**Comment by rwalk651** [comment]
Changed base to `main` since `db_data_handling` was merged.

**Pull request merged**
